"""fix customer document uniqueness

Revision ID: addce4cf3e26
Revises: 6e21cadd0070
Create Date: 2026-08-08 16:29:51.350991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'addce4cf3e26'
down_revision = '6e21cadd0070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_document_number'))
        batch_op.create_unique_constraint('uq_customer_document', ['document_type_id', 'document_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customer_document', type_='unique')
        batch_op.create_index(batch_op.f('ix_customers_document_number'), ['document_number'], unique=1)

    # ### end Alembic commands ###
